[[headers]]
  for = "/*.glb"
  [headers.values]
    Content-Type = "model/gltf-binary"
    Access-Control-Allow-Origin = "*"

[[headers]]
  for = "/models/draco/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
